include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  task-execution {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "task-execution-dlq"
      maxReceiveCount = 3
    }
  }
  task-execution-dlq {}
}
