/* This file is normally (re)generated by SST on `sst dev`/`sst deploy`.
   A stub is checked in so editors and typecheck work before first deploy.
   Application code does NOT read Resource — config arrives via env vars. */
import "sst";
declare module "sst" {
  export interface Resource {
    ApiToken: { type: "sst.sst.Secret"; value: string };
    EchoProviderApiKey: { type: "sst.sst.Secret"; value: string };
    MongoUrl: { type: "sst.sst.Secret"; value: string };
    PostgresUrl: { type: "sst.sst.Secret"; value: string };
    TaskDlq: { type: "sst.aws.Queue"; url: string };
    TaskQueue: { type: "sst.aws.Queue"; url: string };
  }
}
export {};
